spring.application.name=parking

spring.datasource.url=jdbc:postgresql://localhost:5432/parking
spring.datasource.username=postgres
spring.datasource.password=Rubrub@321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# TODO: change the token secret key
jwt.secret=Q7mN2xV9kL4pR8sT1wY6uI3oP5aD0fG2hJ9cK7nM4qX8zB6vC1eS5rT0yU2iO9pL
jwt.expiration=3600000

logging.level.org.springframework.security=DEBUG